# Application Name
spring.application.name=demo

# Server Port
server.port=8080

# Enable H2 Console
spring.h2.console.enabled=true

# H2 Database URL
spring.datasource.url=jdbc:h2:mem:testdb

# Driver
spring.datasource.driver-class-name=org.h2.Driver

# Username
spring.datasource.username=sa

# Password
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update

# Show SQL
spring.jpa.show-sql=true

# Pretty SQL
spring.jpa.properties.hibernate.format_sql=true